### ISSUE TITLE
Choosing multiple regex in the filters array not working

### ISSUE THREAD

**Issue by joshuawaheed** [carstenschaefer/gulp-delete-lines#7]
Hello,

Below is a code of how I've currently setup this function. For some reason on compilation the lines aren't being removed.

    // ...
    .pipe(deleteLines({
        'filters': [
            /<base\s+href=["']/i,
            /<script\s+src=["']https:\/\/ajax\.googleapis\.com\/ajax\/libs\/jquery\/1\.12\.2\/jquery\.min\.js["']/i
        ]
    }))
    // ...

However, when I reduce the array to 1 item like below, it works.

    // ...
    .pipe(deleteLines({
        'filters': [
            /<base\s+href=["']/i
        ]
    }))
    // ...

**Comment by YodasWs** [comment]
I'm having the same problem. And instead each line of the file is duplicated!

**Comment by carstenschaefer** [comment]
thanks a lot for your PR!
